name: nodejs_flutter
description: "Aplikasi Bank Sampah – Kelola sampah jadi berkah"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # API Request
  http: ^1.1.0
  
  # Multipart upload image
  http_parser: ^4.0.2
  
  # Ambil gambar dari kamera/gallery
  image_picker: ^1.0.4
  
  # Simpan token login JWT
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Generate icon aplikasi otomatis
  flutter_launcher_icons: ^0.13.1

# Konfigurasi flutter_launcher_icons (ganti icon)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"     # background putih
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  
  # Folder assets untuk icon dan gambar lainnya
  assets:
    - assets/