name: ruang_nada
description: "Aplikasi manajemen alat musik Ruang Nada"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  camera: ^0.11.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ruang_nada.png"
  adaptive_icon_background: "#1A2A3A"
  adaptive_icon_foreground: "assets/ruang_nada.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
